from django.contrib.contenttypes.models import ContentType
from django.test import SimpleTestCase
from test_app.models import (
    M2MOwnerModel,
    M2MTagModel,
)

from django_async_backend.db.models.manager import AsyncManager
from django_async_backend.db.models.patch import (
    _ASYNC_MIXIN_MEMBERS,
    _ORIGINAL_MODEL_ATTRS,
)
from django_async_backend.test import AsyncioTestCase


class PatchModelTest(SimpleTestCase):
    def test_patch_does_not_override_existing_model_attrs(self):
        """Every member the patch copies onto ``Model`` must be new -- it must
        not shadow an attribute the pristine ``Model`` already had. If this
        fails, rename the offending member so the patch can never clobber
        Django's own behavior.
        """
        collisions = sorted(set(_ASYNC_MIXIN_MEMBERS) & _ORIGINAL_MODEL_ATTRS)
        self.assertEqual(
            collisions,
            [],
            "These members would override existing Model attributes: "
            f"{collisions}. Rename them.",
        )


class PatchAsyncManagerTest(AsyncioTestCase):
    async def test_autogenerated_through_model_has_working_async_manager(self):
        through = M2MOwnerModel.tags.through

        # The patch reached the auto-created model.
        self.assertTrue(hasattr(through, "async_save"))
        self.assertTrue(hasattr(through, "async_delete"))
        self.assertIsInstance(through.async_objects, AsyncManager)
        self.assertIsInstance(through._async_base_manager, AsyncManager)

        owner = await M2MOwnerModel.async_objects.acreate(name="owner")
        tag = await M2MTagModel.async_objects.acreate(name="tag")
        await through.async_objects.acreate(
            m2mownermodel=owner, m2mtagmodel=tag
        )

        self.assertEqual(await through.async_objects.acount(), 1)
        self.assertTrue(
            await through.async_objects.filter(m2mownermodel=owner).aexists()
        )

    async def test_model_without_mixin_has_working_async_manager(self):
        self.assertTrue(hasattr(ContentType, "async_save"))
        self.assertIsInstance(ContentType.async_objects, AsyncManager)
        self.assertIsInstance(ContentType._async_base_manager, AsyncManager)

        created = await ContentType.async_objects.acreate(
            app_label="patch_test", model="widget"
        )
        stored = await ContentType.async_objects.aget(pk=created.pk)
        self.assertEqual(stored.model, "widget")

        await stored.async_delete()
        self.assertFalse(
            await ContentType.async_objects.filter(pk=created.pk).aexists()
        )
