pathname: db/models/query.pyд

module:
  new_imports:
    - "from django_async_backend.db.models import sql as async_sql"

  functions:
    prefetch_related_objects:
      to_async: true

    # todo:
    # aprefetch_related_objects:
    #   remove: true

  classes:
    QuerySet:
      assigns:
        - target:
            name: create
          remove: true

        - target:
            name: bulk_update
          remove: true

        - target:
            name: get_or_create
          remove: true

        - target:
            name: update
          remove: true

        - target:
            name: update_or_create
          remove: true

        - target:
            name: bulk_create
          remove: true

        - target:
            name: delete
          remove: true

      methods:
        __init__:
          calls:
            - func:
                attr: Query
              rename:
                func:
                  value: async_sql

        # __getitem__:
        #   add_raw_top:
        #     - |
        #       async def get_item():
        #           await qs._fetch_all()
        #           return qs._result_cache[0]
        #     - |
        #       async def get_item_from_cache():
        #           # Even if the object exists in the cache, we return a coroutine
        #           # to maintain consistent behavior when the object is not in
        #           # the cache.
        #           return self._result_cache[k]
        #   return_blocks:
        #     - replace_raw: 'get_item_from_cache()'
        #       call:
        #         func:
        #           value: self
        #           attr: _result_cache

        _prefetch_related_objects:
          to_async: true
          calls:
            - name: prefetch_related_objects
              to_await: true

        aexplain:
          remove: True

        aget:
          remove: true

        acreate:
          remove: true

        abulk_create:
          remove: true

        abulk_update:
          remove: true

        aget_or_create:
          remove: true

        aupdate_or_create:
          remove: true

        aaggregate:
          remove: true

        acount:
          remove: true

        aexists:
          remove: true

        acontains:
          remove: true

        afirst:
          remove: true

        alast:
          remove: true

        aearliest:
          remove: true

        alatest:
          remove: true

        ain_bulk:
          remove: true

        adelete:
          remove: true

        aupdate:
          remove: true

        aiterator:
          remove: true

        __iter__:
          remove: true

        __len__:
          remove: true

        __bool__:
          remove: true

        __repr__:
          remove: true

        __getstate__:
          remove: true

        __setstate__:
          remove: true

        explain:
          to_async: true
          rename: aexplain

          calls:
            - func:
                attr: explain
              to_await: true

        get:
          to_async: true
          rename: aget

        create:
          to_async: true
          rename: acreate

        bulk_create:
          to_async: true
          rename: abulk_create

        bulk_update:
          to_async: true
          rename: abulk_update

        get_or_create:
          to_async: true
          rename: aget_or_create

        update_or_create:
          to_async: true
          rename: aupdate_or_create

        aggregate:
          to_async: true
          rename: aaggregate

          calls:
            - func:
                attr: chain
              to_await: true

        count:
          to_async: true
          rename: acount
          calls:
            - func:
                attr: get_count
              to_await: true

        exists:
          to_async: true
          rename: aexists

        contains:
          to_async: true
          rename: acontains

        first:
          to_async: true
          rename: afirst
          for_statements:
            - target: obj
              to_async: true

        last:
          to_async: true
          rename: alast
          for_statements:
            - target: obj
              to_async: true

        earliest:
          to_async: true
          rename: aearliest

        latest:
          to_async: true
          rename: alatest

        in_bulk:
          to_async: true
          rename: ain_bulk

        delete:
          to_async: true
          rename: adelete

        update:
          to_async: true
          rename: aupdate
          calls:
            - func:
                attr: execute_sql
              to_await: true

        iterator:
          to_async: true
          rename: aiterator

        _raw_delete:
          to_async: true
          calls:
            - func:
                attr: execute_sql
              to_await: true

        _update:
          to_async: true
          calls:
            - func:
                attr: execute_sql
              to_await: true

        _insert:
          to_async: true
          calls:
            - func:
                attr: execute_sql
              to_await: true

        __aiter__:
          calls:
            - name: sync_to_async
              replace_raw: self._fetch_all

        _fetch_all:
          to_async: true
          calls:
            - name: list
              replace_raw: list([i async for i in self._iterable_class(self)])
            - func:
                value: self
                attr: _prefetch_related_objects
              to_await: true

    BaseIterable:
      methods:
        _async_generator:
          remove: true

        __aiter__:
          remove: true

    ModelIterable:
      methods:
        __iter__:
          rename: __aiter__
          to_async: true
          calls:
            - func:
                attr: results_iter
              to_await: true
            - func:
                attr: execute_sql
              to_await: true

    RawModelIterable:
      methods:
        __iter__:
          rename: __aiter__
          to_async: true

    ValuesIterable:
      methods:
        __iter__:
          rename: __aiter__
          to_async: true
          calls:
            - func:
                attr: results_iter
              to_await: true

    ValuesListIterable:
      methods:
        __iter__:
          rename: __aiter__
          to_async: true
          calls:
            - func:
                attr: results_iter
              to_await: true

    NamedValuesListIterable:
      methods:
        __iter__:
          rename: __aiter__
          to_async: true
          calls:
            - func:
                attr: __iter__
              to_await: true
              rename:
                func:
                  attr: __aiter__

    FlatValuesListIterable:
      methods:
        __iter__:
          rename: __aiter__
          to_async: true
          calls:
            - func:
                attr: results_iter
              to_await: true
