# Generated by Django 6.1.dev20260708155653 on 2026-07-08 16:30

import uuid

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "parent_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DbDefaultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ts", models.IntegerField(db_default=models.Value(7))),
            ],
            options={
                "db_table": "db_default_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="GetLatestByModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "latest_by",
                "get_latest_by": "id",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="OrderParentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "order_parent_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PkOnlyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "pk_only_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SaveParentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "save_parent_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SaveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "save_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SelectOnSaveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "select_on_save_model",
                "select_on_save": True,
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="UuidPkModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "uuid_pk_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ChildModel",
            fields=[
                (
                    "parentmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_app.parentmodel",
                    ),
                ),
                ("child_value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "child_model",
            },
            bases=("test_app.parentmodel",),
        ),
        migrations.CreateModel(
            name="GenericFkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "generic_fk_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SaveChildModel",
            fields=[
                (
                    "saveparentmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_app.saveparentmodel",
                    ),
                ),
                ("child_value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "save_child_model",
            },
            bases=("test_app.saveparentmodel",),
        ),
        migrations.CreateModel(
            name="RelatedSaveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "fk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="test_app.savemodel",
                    ),
                ),
                (
                    "o2o",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="test_app.savemodel",
                    ),
                ),
            ],
            options={
                "db_table": "related_save_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SaveProxyModel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("test_app.savemodel",),
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.IntegerField(null=True)),
                (
                    "relative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relatives",
                        to="test_app.testmodel",
                    ),
                ),
            ],
            options={
                "db_table": "test_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="OrderItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="test_app.orderparentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "order_item_model",
                "order_with_respect_to": "parent",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
