# Generated by Django 6.0.2 on 2026-08-03 17:39

import django.db.models.deletion
import test_app.models
from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateOrCreateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.IntegerField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related",
                    test_app.models.TouchingForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="test_app.savemodel",
                    ),
                ),
            ],
            options={
                "db_table": "update_or_create_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
