# Generated by Django 6.1.dev20260709145112 on 2026-07-09 18:13

from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_getorcreatemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbDefaultPkModel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_default=models.Value(1),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "db_default_pk_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
