# Generated by Django 6.0.2 on 2026-08-04 03:50

from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_updateorcreatemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("date", models.DateField(null=True)),
                ("datetime", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "dates_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
