# Generated by Django 6.1.dev20260711222452 on 2026-07-25 18:33

from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_dbdefaultpkmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="M2MTagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "m2m_tag_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="M2MOwnerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="owners", to="test_app.m2mtagmodel"
                    ),
                ),
            ],
            options={
                "db_table": "m2m_owner_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
