# Generated by Django 6.0.2 on 2026-08-04 16:55

from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_datesmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultOrderingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "default_ordering_model",
                "ordering": ["name"],
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
