# Generated by Django 6.0.2 on 2026-07-13 20:09

import django.db.models.deletion
import django_async_backend.db.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_dbdefaultpkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'delete_author_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteTaggedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'delete_tagged_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='test_app.deleteauthormodel')),
            ],
            options={
                'db_table': 'delete_book_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteCascadeRestrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cascade_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cascade_restrict_refs', to='test_app.deleteauthormodel')),
                ('restrict_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='restricted_via_cascade_refs', to='test_app.deleteauthormodel')),
            ],
            options={
                'db_table': 'delete_cascade_restrict_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteProtectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_refs', to='test_app.deleteauthormodel')),
            ],
            options={
                'db_table': 'delete_protected_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteRestrictedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='restricted_refs', to='test_app.deleteauthormodel')),
            ],
            options={
                'db_table': 'delete_restricted_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='test_app.deletebookmodel')),
            ],
            options={
                'db_table': 'delete_review_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteSetDefaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setdefault_refs', to='test_app.deleteauthormodel')),
            ],
            options={
                'db_table': 'delete_setdefault_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeleteSetNullModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setnull_refs', to='test_app.deleteauthormodel')),
            ],
            options={
                'db_table': 'delete_setnull_model',
            },
            bases=(django_async_backend.db.models.base.AsyncModelMixin, models.Model),
        ),
    ]
