# Generated by Django 6.0.2 on 2026-07-28 17:50

import test_app.models
from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0006_genericrelationmodel_genericchildmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetCallableChildModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(
                            test_app.models.get_set_callable_parent
                        ),
                        related_name="set_callable_children",
                        to="test_app.deletemodel",
                    ),
                ),
            ],
            options={
                "db_table": "set_callable_child_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
