# Generated by Django 6.0.2 on 2026-08-01 17:01

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0008_multileveldeletemodel_multilevelsetnullchildmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrandChildModel",
            fields=[
                (
                    "childmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_app.childmodel",
                    ),
                ),
                ("grand_child_value", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "grand_child_model",
            },
            bases=("test_app.childmodel",),
        ),
    ]
